FROM brass:base
MAINTAINER Chris Timperley "christimperley@gmail.com"

# Install modified version of Daikon to /daikon
RUN mkdir /daikon && cd /daikon &&\
    wget http://plse.cs.washington.edu/daikon/download/daikon-5.4.2.tar.gz &&\
    tar zxf daikon-5.4.2.tar.gz
